# Streamlit Google Sheets Connection Configuration
# This file tells Streamlit how to connect to your Google Sheet

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1NFfol3Incp-80m4JYojoJ--yzQYY2IgWvWz5GiUcQGY/edit?gid=897113735#gid=897113735"
type = "public"
